version: "2"

services:
  compiler:
    context: .
    ports:
      - 3000:3000
    networks:
      - compiler-network
    volumes:
      - build-cache:/app/src/build-cache
      - sketch-cache:/tmp

  cleanup:
    image: alpine:latest
    command: |
      /bin/sh -c "
        set -e
        IFS=$$'\n\t'
        eval exec find /tmp/* -type d -maxdepth 0 -mmin +60 | xargs rm -rf
      "
    volumes:
      - sketch-cache:/tmp

networks:
  compiler-network:

volumes:
  build-cache:
  sketch-cache:
